# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "cargo"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "composer"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "devcontainers"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "mix"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "elm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "pub"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "swift"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "terraform"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
